### ISSUE TITLE
PowerMatcher with Intellij Idea

### ISSUE THREAD

**Issue by kbakcgi** [flexiblepower/powermatcher#204]
Hello, is there any way to run that on Intellij Idea?

regards, 
KB

**Comment by wilcowijbrandi** [comment]
Good question! PowerMatcher (and EF-Pi) rely on bnd (http://aqute.biz/Code/bnd), and we mainly use Eclipse because Bndtools (http://bndtools.org/) seems to be the best way to do bnd. It seems that IntelliJ IDEA has a way to import bnd projects (https://www.jetbrains.com/help/idea/2016.1/osgi.html), but I have no experience with that. I'd say: give it a try and let us know!

**Comment by kbakcgi** [comment]
But is it possible to build it using gradle?

**Comment by wilcowijbrandi** [comment]
Yes, it definitely is! You can build everything with gradle, but having a good IDE that can help you with bnd and osgi (e.g. resolving dependencies in a .bndrun file) can make your live a lot easier!

**Comment by kbakcgi** [comment]
OK, the problem was i missed to initialize git submodules, now it works:) Thanks for help!
